version: "3.9"

services:
  web:
    build: .
    command: bash -c "cd src/ && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/backend
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14.5-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    env_file:
      - src/.env

volumes:
  postgres_data: