"""Record model

Revision ID: 34756079544f
Revises: 42494b5bec14
Create Date: 2023-05-20 13:30:29.622799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34756079544f'
down_revision = '42494b5bec14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('file', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_file'), 'record', ['file'], unique=False)
    op.create_index(op.f('ix_record_id'), 'record', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_id'), table_name='record')
    op.drop_index(op.f('ix_record_file'), table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
